name: build and run tests
on:
  push:
    branches: [ cpp_refactor ]
  pull_request:
    branches: [ cpp_refactor ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      # install dependency mlpack
      - name: Install mlpack
        run: |
          cd external/mlpack
          mkdir build
          cd build
          cmake -DDEBUG=OFF -DDOWNLOAD_DEPENDENCIES=ON -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF -DBUILD_JULIA_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_CLI_EXECUTABLES=OFF -DBUILD_TESTS=OFF ../
          sudo make install
      - name: Build ALF
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake ..
          make
      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          cd build
          ctest
          
      
